name: Ciencia de Datos - GECI
on: [pull_request, push]

jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
      - name: Copia repositorio
        uses: actions/checkout@v2
      - name: Construye imagen
        run: docker build --tag islasgeci/ejemplo_typescript .
      - name: Run tests
        run: docker run islasgeci/ejemplo_typescript make tests
      - name: Run mutation
        run: docker run islasgeci/ejemplo_typescript make mutation
